import { LanguageProvider } from "@/context/LanguageContext";
import type { Metadata } from "next";
import { Bebas_Neue, Cairo, Inter, Lexend } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { FloatingAgent } from "@/components/FloatingAgent";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const cairo = Cairo({ subsets: ["latin"], variable: "--font-arabic" });
const lexend = Lexend({ subsets: ["latin"], variable: "--font-heading" });
const bebasNeue = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-display",
});

export const metadata: Metadata = {
  title: "Next House",
  description: "Generated by Next House",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${cairo.variable} ${lexend.variable} ${bebasNeue.variable}`}
    >
      <body>
        <LanguageProvider>
          <Navbar />
          <main className="min-h-[100dvh]">{children}</main>
          <Footer />
          <FloatingAgent />
        </LanguageProvider>
      </body>
    </html>
  );
}
